<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
        <!-- LINKS -->
        <link rel="icon" type="image/x-icon" href="/storage/ico">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <script>
            <?php
            require_once $_SERVER['DOCUMENT_ROOT'] . '/biblio/jquery-3.5.1.min.js';
            ?>
        </script>
        <style>
            <?php
            require_once $_SERVER['DOCUMENT_ROOT'] . '/biblio/bootstrap.min.css';
            ?>
        </style>
        <!-- Home style -->
        <style>
            button {
                background-color: #ddd;
                border: none;
                padding: 15px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 20px;
            }
            body {
                padding: 0;
                margin: 0;
                font-size: 18px;
                background-color:  #eee;
            }
            .fake-textarea {
                -moz-appearance: textfield;
                -webkit-appearance: textfield;
                font: -moz-field;
                font: -webkit-small-control;
            }

            .textarea, textarea {
                margin-bottom:1em;
                width: 100%;
                height: 150px;
                padding: 12px 20px;
                box-sizing: border-box;
                border: 2px solid #ccc;
                border-radius: 4px;
                background-color: #f8f8f8;
                font-size: 16px;
                resize: none;
            }




            .button {
            margin: .25rem;
            font-size: 18px;
            cursor: pointer;
            padding: .25rem .5rem .25rem .5rem;
            }

            table.request > tbody > tr > td > input[type="checkbox"] {
            border: 1px solid white;
            margin-left: 2rem;
            width: 1.2em;
            height: 1.2em;
            padding: 18px;
            }

            /* Dropdown Button */
            .dropbtn {
            font-size: 1em;
            background-color: #8B0000;
            color: white;
            padding: .75em;
            border: none;
            font-family: Helvetica;
            font-weight: bold;
            cursor: pointer;
            white-space: nowrap;
            }

            /* Dropdown button on hover & focus */
            .dropbtn:hover,
            .dropbtn:focus {
                background-color: #FF8C00;
            }

            /* The container <div> - needed to position the dropdown content */
            .dropdown {
            float: right;
            }

            /* Dropdown Content (Hidden by Default) */
            .dropdown-content {
            /* height: 27px; */
            display: none;
            position: absolute;
            background-color: #f1f1f1;
            min-width: 260px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            right: 0;
            z-index: 1;
            white-space: nowrap;
            }

            /* Links inside the dropdown */
            .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            }

            /* Change color of dropdown links on hover */
            .dropdown-content a:hover {
            background-color: #E9967A;
            }

            /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
            .show {
            display: block;
            }

            /* -------------------- */
            /* Table structure css */
            /* ------------------ */
            table {
            border-collapse: collapse;
            
            font-size: 18px;
            font-family: Helvetica;
            width: 90%;
            }

            table.userCredentials,
            table.logo {
            margin-top: 1rem;
            margin-bottom: 1rem;
            }

            table.userCredentials>thead {
            background: #DC143C;

            }

            table.userCredentials>tbody {
            background: #FFF8DC;
            }

            table.userCredentials>thead>tr>th,
            table.userCredentials>tbody>tr>td {
            border: 3px solid #8B0000;
            border-radius: 30px;
            min-height: 45px;
            padding: .75rem;
            text-align: center;
            }

            table.logo>thead>tr>th.header {
            font-size: 1.75em;
            padding: 0;
            text-align: left;
            padding-top: 1rem;
            color: red;
            text-transform: uppercase;
            font-weight: bold;
            }

            table.logo>thead>tr>th.logoImg {
            text-align: left;
            }

            /* ------ */
            /* Utils */
            /* ---- */
            .colorBlue {
            color: #124191
            }

            .colorRed {
            color: #cc2424
            }

            .colorYellow {
            color: #dab12d
            }

            .colorGreen {
            color: #48c003
            }

            .colorGray {
            color: #a7a3a3;
            }

            .colorOrange {
            color: #F79646;
            }

            .paddingLeft {
            padding-left: 3rem;
            }

            .paddingTop {
            padding-top: 1.5rem;
            }

            .paddingBottom {
            padding-top: 1.5rem;
            }
            .textCenter {
            text-align: center;
            }

            .marginBottom {
            margin-bottom: 1rem;
            }
        </styLe>
        <!-- CSS DIALOG BOX -->
        <?= (isset($header)) ? $header : '' ?>

        <title><?= $title ?></title>

        <!-- CSS DIALOG BOX -->
        <style>
                /**
            * Item
            * ----------------------------------------------------------------------------------
            */
            .msgpopup-box {
                overflow: hidden;
                display: none;
            }
            .msgpopup-wrap {
                position: relative;
            }
            .msgpopup-item {
                position: relative;
                font-size: 14px;
                width: 100%;
                max-width: 100%;
                box-sizing: border-box;
                text-align: center;
            }

            /**
            * Default position
            * ----------------------------------------------------------------------------------
            */
            .msgpopup-container {
                position: fixed;
                right: 0;
                width: 350px;
                bottom: 5px;
                z-index: 999;
            }
            .msgpopup-container .msgpopup-box-clone-output {
                width: 100%;
                overflow: auto;
                max-height: 100vh;
            }
            .msgpopup-container .msgpopup-wrap {
                right: -360px;
                transition: right 0.5s ease 0s;
            }
            .msgpopup-container .msgpopup-wrap.msgpopup-wrap-visible {
                right: 0;
            }

            /**
            * Theme
            * ----------------------------------------------------------------------------------
            */
            .msgpopup-theme-default .msgpopup-close-x {
                display: inline-flex;
                justify-content: center;
                align-items: center;
                line-height: inherit;
                font-size: inherit;
                cursor: pointer;
                border-radius: 50%;
                text-align: center;
                position: absolute;
                right: 3px;
                top: 0;
                padding: 4px;
                width: 16px;
                height: 16px;
                background-color: #CA1C3B;
            }
            .msgpopup-theme-default .msgpopup-close-x:before {
                content: '';
                position: absolute;
                left: 6px;
                top: 6px;
                right: 6px;
                bottom: 6px;
                background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAABsUlEQVRogc3aMU/DMBCG4fxRNtgjhk6oSGROu5WFInVBjGz8vJehsnCtOD3H9t19Y3RJ/TS2m5w6DEmAPXBJj3sJcALme0UP/OeoNDZxgJdofGOuKEa4wySIZUwG4QaTQdxigNeVopCDIWIvGN88AF+CQhOM8EsG+A0nHIUnqE0z1qdTnEt6ohvMZoQnTDUiutBBeKHmawbZwgY4Sy8ovTPNMMgX9mfphdWmGa2mkyWmO0IDo4aIPrD5BkDrhV3wwc02AHot7A6Y7DRDezr1wLhB1GDcIaKBSTeAZ+BJWNt2YRdgpHdGkj4LWxnjo9lRifGBCNmI8YUI4bqwpXmzHm82wGMBZGc93sUg/52IY95quslGhC9MJcIHBvmjuCQ2TUDkj+ITsHOJYcMDIA5aTdUId5gahBsMDd+xsWoC0uEdG+0mIB3f7AowddOsJ0INo4HojsGgeUbrDQDD5hmtNgActGwKMMvTzAOiGuMJsRkDvAtPUG+eId8AvgdgFhSaNc+Q3ZlzKB5XisxbNncwU1q8hDFHhGQwU6549IgISTDLiKh4Bn6UxlYcrv+d+UiP/wGfJ1F2pYUZrQAAAABJRU5ErkJggg==');
                background-size: cover;
                background-position: center center;
            }

            .msgpopup-theme-default .msgpopup-wrap {
                padding: 5px 10px 0 10px;
                margin-bottom: 7px;
            }
            .msgpopup-theme-default .msgpopup-content {
                padding: 15px;
            }
            .msgpopup-theme-default .msgpopup-type {
                border: 1px solid;
                border-radius: 3px;
                font-weight: bold;
                box-shadow: 0 5px 5px rgba(0,0,0,0.1);
            }
            .msgpopup-theme-default .msgpopup-normal {
                color: #5B6D72;
                background: #FCFCFD;
            }
            .msgpopup-theme-default .msgpopup-success {
                color: #13A20A;
                background: #F9FFFA;
            }
            .msgpopup-theme-default .msgpopup-error {
                color: #E11919;
                background: #FFF7F7;
            }
            .msgpopup-theme-default .msgpopup-info {
                color: #31BFDB;
                background: #EDFCFF;
            }
            .msgpopup-theme-default .msgpopup-alert {
                color: #F2BC00;
                background: #FFFFED;
            }
            /* Example 2 */
            .example-box-2 {
                background-color: #FAFAFA;
                border-radius: 3px;
                overflow: hidden;
            }
            .example-title-2 {
                display: flex;
                color: #FFFFFF;
                justify-content: center;
                align-items: center;
                font-family: Helvetica;
                font-weight: bold;
                font-size: 18px;
                margin: 0;
                padding: 10px;
                background: var(--blue);
            }
            .example-icon-2 {
                display: block;
                max-width: 30px;
                margin-right: 15px;
            }
            .example-content-2 {
                font-family: Helvetica;
                font-weight: normal;
                font-size: 15px;
                padding: 14px
            }
            .example-buttons-2 {
                display: flex;
                font-family: Helvetica;
                font-weight: normal;
                justify-content: flex-end;
                padding: 0 8px 12px;
            }
            .example-box-2 button {
                padding: 10px 15px;
                margin: 5px;
            }
            .example-box-2 .btn-info {
                margin-right: auto;
            }

        </style>
        <!-- JQUERY DIALOG BOX -->
        <script>
            function sanitizeAndSubmit() {
                var textareas = document.querySelectorAll('textarea');
                for (var i = 0; i < textareas.length; i++) {
                    var textareaValue = textareas[i].value;
                    var sanitizedValue = textareaValue.replace(/<[^>]*>/g, '');
                    textareas[i].value = sanitizedValue;
    
                    console.log(sanitizedValue)
                }
            }
    


            $(function () {
                $.fn.msgpopup = function( options ){

            var opt = $.extend({
                text: '',
                type: 'normal',
                time: 5000,
                class: '',
                x: true,
                removeContainerOnClose: false,
                containerCheckItemBeforeRemove: true,
                success: null,
                id: false,
                scrollToBottomOnNewMessage: true,
                custom: false,

                closeFunc: true,
                mouseoverFunc: false,
                mouseoutFunc: false,
                beforeShowFunc: false,
                afterShowFunc: false,
                clickFunc: false,
                beforeRemoveFunc: false,
                afterRemoveFunc: false,

                themeClass: 'msgpopup-theme-default',
                defaultTypeClass: 'msgpopup-type',
                wrapVisibleClass: 'msgpopup-wrap-visible',
                appendTo: 'body',

                elToCloneData: 'data-msgpopup-to-clone',
                containerData: 'data-msgpopup-container',
                containerClass: 'msgpopup-container',
                boxContentData: 'data-msgpopup-content',
                boxContentClass: 'msgpopup-content',
                boxTextData: 'data-msgpopup-text',
                boxTextClass: 'msgpopup-text',
                boxCloneOutputData: 'data-msgpopup-box-clone-output',
                boxCloneOutputClass: 'msgpopup-box-clone-output',
                wrapData: 'data-msgpopup-wrap',
                wrapClass: 'msgpopup-wrap',
                itemData: 'data-msgpopup-item',
                itemClass: 'msgpopup-item',
                boxData: 'data-msgpopup-box',
                boxClass: 'msgpopup-box',
            }, options);

            /**
             * Check func exists before exec
             * ----------------------------------------------------------------------------------
             */
            var execFunc = function(func, param){
                if(typeof(window[func]) === 'function') {
                    window[func](param);
                } else if(func !== false) {
                    console.log('MSGPOPUP: function "'+func+'" doesn\'t exist.');
                }
            }

            /**
             * Init function
             * ----------------------------------------------------------------------------------
             */
            var init = function() {
                var checkIfMessagePopupHasInit = $('['+opt.containerData+']');
                if(checkIfMessagePopupHasInit.length <= 0) {
                    $(opt.appendTo).append('\
                    <div '+opt.containerData+' class="msgpopup '+opt.containerClass+' '+opt.themeClass+'">\
                        <div '+opt.boxCloneOutputData+' class="'+opt.boxCloneOutputClass+'"></div>\
                        <div '+opt.elToCloneData+' '+opt.boxData+' class="'+opt.boxClass+'">\
                            <div '+opt.wrapData+' class="'+opt.wrapClass+'">\
                                <div '+opt.itemData+' class="'+opt.itemClass+'">\
                                    <div '+opt.boxContentData+' class="'+opt.boxContentClass+'">\
                                        <div '+opt.boxTextData+' class="'+opt.boxTextClass+'"></div>\
                                    </div>\
                                </div>\
                            </div>\
                        </div>\
                    </div>');
                }

                if(opt.beforeShowFunc) {
                    execFunc(opt.beforeShowFunc, {
                        opt: opt,
                        item: msgClone,
                        event: e
                    });
                }

                show();

                return this;
            }

            /**
             * Show function
             * ----------------------------------------------------------------------------------
             */
            var show = function(){

                // Clone default
                var container = $('['+opt.containerData+']');
                var msgClone = $.extend(true, {}, container.find('['+opt.elToCloneData+']').clone());

                // Message type
                if(opt.success === true) {
                    msgType = 'success';
                } else if(opt.success === false) {
                    msgType = 'error';
                } else {
                    var msgType = opt.type;
                }

                // Popup Mouse Hover Func
                if(opt.mouseoverFunc) {
                    $(document).on({
                        mouseenter: function(e) {
                            execFunc(opt.mouseoverFunc, {
                                opt: opt,
                                item: msgClone,
                                event: e
                            });
                        }
                    }, msgClone);
                }

                // Popup Mouse Leave Func
                if(opt.mouseoutFunc) {
                    $(document).on({
                        mouseleave: function(e) {
                            execFunc(opt.mouseoutFunc, {
                                opt: opt,
                                item: msgClone,
                                event: e
                            });
                        }
                    }, msgClone);
                }

                // Popup click Func
                if(opt.clickFunc) {
                    $(document).on({
                        click: function(e) {
                            execFunc(opt.clickFunc, {
                                opt: opt,
                                item: msgClone,
                                event: e
                            });
                        }
                    }, msgClone);
                }

                // Add close button
                if(opt.x === true) {
                    msgClone.find('['+opt.wrapData+']').append('<span class="msgpopup-close-container"><span data-msgpopup-close class="msgpopup-close-x"></span></span>');
                }

                // Insert text
                msgClone
                .find('['+opt.boxTextData+']')
                .html(opt.text);

                // Custom doesn't have default class
                if(opt.custom) {
                    msgClone
                    .find('['+opt.itemData+']')
                    .removeClass(opt.itemClass)
                    .removeClass(opt.defaultTypeClass)
                    .find('['+opt.boxContentData+']')
                    .removeClass(opt.boxContentClass)
                } else {
                    msgClone
                    .find('['+opt.itemData+']')
                    .addClass((opt.defaultTypeClass === false ? '' : opt.defaultTypeClass)+' msgpopup-'+msgType+' '+msgType);
                }

                // Config to cloned
                msgClone
                .removeAttr(opt.elToCloneData)
                .attr('data-msgpopup-id', (opt.id ? opt.id : ''))
                .appendTo('['+opt.boxCloneOutputData+']')
                .slideDown()
                .removeClass('msgpopup-clone')
                .find('['+opt.itemData+']')
                .addClass(opt.class);

                // Finally, show :)
                msgClone
                .find('['+opt.wrapData+']')
                .addClass(opt.wrapVisibleClass);

                // Scroll to bottom if overflow
                if(opt.scrollToBottomOnNewMessage) {
                    var container = $('['+opt.boxCloneOutputData+']');
                    container.stop().animate({
                        scrollTop: container.prop('scrollHeight')
                    }, null);
                }

                // Close func
                if(opt.closeFunc) {
                    msgClone.find('[data-msgpopup-close]').click(function(){
                        if(opt.closeFunc === true) {
                            var item = $(this).parents('['+opt.boxData+']').eq(0);
                            remove(item);
                        } else {
                            execFunc(opt.closeFunc, {
                                opt: opt,
                                item: msgClone,
                            });
                        }
                    });
                }

                // Time to remove
                if(typeof(opt.time) === 'number') {
                    setTimeout(function(){
                        remove(msgClone);
                    }, opt.time);
                }

                // After show func
                if(opt.afterShowFunc) {
                    execFunc(opt.afterShowFunc, {
                        opt: opt,
                        item: msgClone,
                        event: e
                    });
                }

                return this;
            }

            /**
             * Remove clone function
             * ----------------------------------------------------------------------------------
             */
            var remove = function(item) {

                var container = item.parents('['+opt.containerData+']').eq(0);
                item.find('['+opt.wrapData+']').removeClass(opt.wrapVisibleClass);

                // Before remove func
                if(opt.beforeRemoveFunc) {
                    $(document).on({
                        click: function(e) {
                            execFunc(opt.beforeRemoveFunc, {
                                opt: opt,
                                item: msgClone,
                                event: e
                            });
                        }
                    }, msgClone);
                }

                // Animate to remove
                item.animate({
                    height: 0,
                    padding: 0
                }, null, function(){
                    item.remove();
                    if(opt.removeContainerOnClose) {
                        if(opt.containerCheckItemBeforeRemove) {
                            if(container.find('['+opt.boxCloneOutputData+']').find('['+opt.boxData+']').length <= 0) {
                                container.remove();
                            }
                        }
                    }
                    if(opt.afterRemoveFunc) {
                        $(document).on({
                            click: function(e) {
                                execFunc(opt.afterRemoveFunc, {
                                    opt: opt,
                                    item: msgClone,
                                    event: e
                                });
                            }
                        }, msgClone);
                    }
                });
            }

            init();

            return this;
            }
        })


        </script>

        <script>
            function infoBox(msg) {
                $().msgpopup({
                    type: 'info',
                    text: msg,
                    time: 5000,
                    x: true,
                });
            };
            function successBox(msg) {
                $().msgpopup({
                    type: 'success',
                    text: msg,
                    // closeFunc: 'testEcho',
                    time: 5000,
                    x: true,
                });
            };
            function alertBox(msg) {
                $().msgpopup({
                    type: 'alert',
                    text: msg,
                    time: 7000,
                    x: true,
                });
            };
            function errorBox(msg) {
                $().msgpopup({
                    type: 'error',
                    text: msg,
                    time: 8000,
                    x: true,
                });
            };

            function confirmBox(msg, eid='', boxName='update'){
                var someHtmlCode = '\
                    <div class="example-box-2 border">\
                        <h2 class="example-title-2">\
                            <span>Action requires confirmation</span>\
                        </h2>\
                        <div class="example-content-2">'+msg+'</div>\
                        <div class="example-buttons-2">\
                            <button type="button" class="btn btn-error" data-msgpopup-close >Close</button>\
                            <button type="button" class="btn btn-success" value="'+eid+'" data-msgpopup-close data-btn-message="'+boxName+'">Comfirm!</button>\
                        </div>\
                    </div>';

                $().msgpopup({
                    text: someHtmlCode,
                    custom: true,
                    time: false,
                });
            };
        </script>
    </head>

    <body>
        <header>
            <?php
                require_once $_SERVER["DOCUMENT_ROOT"] . '/templates/header.phtml';
            ?>
        </header>

        <?php
            require_once $body;
        ?>

    </body>
</html>


