<script type="text/javascript" language="javascript">
    var columnsInfo = [{
            'data': 'eid',
            'render': function(eid, type, row) {
                if (row['review'] == 'request') {
                    return '<button class="btn" onclick="window.open(\'/admin/review/request?user=' + eid + '\', \'_self\')"><span class="material-icons">search</span></button>';
                } else {
                    return '<button class="btn" onclick="window.open(\'/admin/review/cert?user=' + eid + '\', \'_self\')"><span class="material-icons">search</span></button>';
                }
            },
            'sortable': false,
        },
        {
            'data': 'eid'
        },
        {
            'data': 'review',
            'render': function(review) {
                if (review == 'cert_check')
                    color = 'colorOrange'
                else
                    color = 'colorGray'
                return '<span class="' + color + '"><b>' + review + '</b></span>';
            }
        },
        {
            'data': 'name'
        },
        {
            'data': 'login'
        },
        {
            'data': 'email'
        },
        {
            'data': 'comments'
        },
        {
            'data': 'manager_id'
        },
        {
            'data': 'delegated_manager_id'
        },
        {
            'data': 'date'
        },
        {
            'data': 'manager_comment'
        },
        {
            'data': 'admin_comment'
        },
        {
            'data': 'training_date1'
        },
        {
            'data': 'training_date2'
        },
        {
            'data': 'bid'
        },
        {
            'data': 'bsid'
        },
        {
            'data': 'building3'
        },
        {
            'data': 'building2'
        },
        {
            'data': 'building1'
        },
        {
            'data': 'room4'
        },
        {
            'data': 'room3'
        },
        {
            'data': 'room2'
        },
        {
            'data': 'room1'
        }
    ];
    var mycoldef = [{
            targets: [0, 16, 17, 18, 19, 20, 21, 22],
            "searchable": false
        },
        {
            targets: [16, 17, 18, 19, 20, 21, 22],
            class: 'choose',
            'render': function(data) {
                if (data)
                    return '<span class="material-icons colorGreen">done</span>';
                else
                    return '<span class="material-icons colorRed">close</span>';
            }
        },
        {
            targets: [6, 10, 11],
            'render': function(data) {
                if (data == 'IMPLICITY_NULL')
                    return '<span class="colorGray">N/A</span>';
                else
                    return '<i>' + data + '</i>';
            }
        },
        {
            targets: [0],
            class: 'button'
        },
        {
            targets: '_all',
            visible: true
        }
    ];
</script>
<main class="box">
    <article class='panel panel-default'>
        <div id='showHideIndicators' class="panel-heading">
            <b>Show/Hidde columns:</b><br />
        </div>
        <div class='panel-heading'>Users awaiting for your approval<br>
            <small class="form-text text-muted">Note: You can hover over the column name for more details.</small>
        </div>
        <div class='panel-body'>
            <div class='table-responsive'>
                <table id="content_table" class='table table-borderoom2 table-striped'>
                    <thead>
                        <tr>
                            <th>Verify</th>
                            <th>Employee ID</th>
                            <th>Review type</th>
                            <th>Name</th>
                            <th>login</th>
                            <th>Email</th>
                            <th>Comments</th>
                            <th>Manager</th>
                            <th>Delegated manager</th>
                            <th>Request/Activation date</th>
                            <th>Manager comments</th>
                            <th>Admin comments</th>
                            <th>training1 date</th>
                            <th>training2 date</th>
                            <th>BID</th>
                            <th>BSID</th>
                            <th>building3</th>
                            <th>building2</th>
                            <th>building1</th>
                            <th>room4</th>
                            <th>room3</th>
                            <th>room2</th>
                            <th>room1</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Verify</th>
                            <th>*Employee ID</th>
                            <th>Review type</th>
                            <th>*Name</th>
                            <th>*Login</th>
                            <th>*Email</th>
                            <th>*Comments</th>
                            <th>*Manager</th>
                            <th>*Delegated manager</th>
                            <th>*Request/Activation date</th>
                            <th>*Manager comments</th>
                            <th>*Admin comments</th>
                            <th>*training1 date</th>
                            <th>*training2 date</th>
                            <th>*BIDd</th>
                            <th>*BSid</th>
                            <th>~building3</th>
                            <th>~building2</th>
                            <th>~building1</th>
                            <th>~room4</th>
                            <th>~room3</th>
                            <th>~room2</th>
                            <th>~room1</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </article>
</main>