<main>
    <article>
        <table class='request' align="center">
            <form action="/request/send" method="post">
                <tbody>
                    <section>
                        <tr>
                            <td>
                                <label for="namer">Name of requester:</label>
                                <input type="text" name="name" value="<?= $lab['name'] ?>" disabled="disabled" />
                                <label  class='paddingLeft' for="manager_name">Manager’s Name:</label>
                                <input type="text" name="manager_name" value="<?= $lab['manager_name'] ?>" disabled="disabled" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="eid">Employee ID:</label>
                                <input type="text" name="eid" size="8" value="<?= $lab['eid'] ?>" disabled="disabled" />

                                <label for="bid" class='paddingLeft'>Your BID:
                                </label>
                                <input id='bid' type="text" name="bid" maxlength="20" size="10" value="<?= $req['bid'] ?>" />
                                <label for="bsid" class='paddingLeft'>Your BSID:
                                </label>
                                <input id='bsid' type="text" name="bsid" maxlength="20" size="10" value="<?= $req['bsid'] ?>" />
                            </td>
                        </tr>
                    </section>
                    <section>
                        <tr>
                            <td class='important'>
                                <input type="checkbox" name="training_attendance" value="<?= $req['training_attendance'] ?>" required />
                                <label for="training_attendance">
                                    I confirm I have completed Introduction training
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td class='important'>
                                <input  type="checkbox" name="ohs" value="<?= $req['ohs'] ?>" required />
                                <label for="ohs">
                                    I confirm I have read all requirements <a href="https://ch.mathworks.com/help/matlab/ref/filter.html#buagwwg-2" target="_blank">MATLAB instructions </a>
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td class='important'>
                                <input  type="checkbox" name="medical" value="<?= $req['medical'] ?>" required />
                                <label for="medical">
                                    I confirm that I am not aware of any medical restrictions that prevent me from entering the buildings.
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td class='important'>
                                <input type="checkbox" name="trainings" value="1"  required />
                                <label for="trainings" >
                                    I confirm that I have completed the following trainings:
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td class='paddingLeft colorGray' style>
                                <i>
                                - Building Security Awareness
                                <br />
                                - MATLAB Training for Building Access
                                </i>

                            </td>
                        </tr>
                    </section>
                    <section>
                        <tr class='paddingTop'>
                            <td>
                                Prior signing this application administrator will verify that access is necessary and requestor meets all requirements.
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" id="building3" name="building3" value="<?= $req['building3'] ?>" />
                                <label for="building3" class='colorGreen'>
                                    Building1
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" id="building2" name="building2" value="<?= $req['building2'] ?>" />
                                <label for="building2" class='colorYellow'>
                                    Building2
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" id="building1" name="building1" value="<?= $req['building1'] ?>" />
                                <label for="building1" class='colorOrange'>
                                    Building1
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td class='paddingTop'>
                                Please note, that access to 
                                <span class='colorBlue'>room4</span>,
                                <span class='colorRed'>room3</span>, 
                                <span class='colorGray'>room2</span> and
                                <span class='colorOrange'>room1</span>
                                rooms require special approval and justification from your manager.
                            </td>

                        </tr>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" id="room4" name="room4" value="<?= $req['room4'] ?>" />
                                <label for="room4" class='colorBlue'>room4</label>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <textarea placeholder="Enter justification" name="room4_justification" rows="4" cols="80"><?= $req['room4_justification'] ?></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" id="room3" name="room3" value="<?= $req['room3'] ?>" />
                                <label for="room3" class='colorRed'> room3</label>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <textarea placeholder="Enter justification" name="room3_justification" rows="4" cols="80"><?= $req['room3_justification'] ?></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" id="room2" name="room2" value="<?= $req['room2'] ?>" />
                                <label for="room2" class='colorGray'>room2</label>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <textarea placeholder="Enter justification" name="room2_justification" rows="4" cols="80"><?= $req['room2_justification'] ?></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="checkbox" id="room1" name="room1" value="<?= $req['room1'] ?>" />
                                <label for="room4" class='colorOrange'>room1</label>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <textarea  placeholder="Enter justification" name="room1_justification" rows="4" cols="80" ><?= $req['room1_justification'] ?></textarea>
                            </td>
                        </tr>
                        <?php if($req['status'] == 1 || $req['status'] == 0): // functional buttons  ?>
                        <tr>
                            <td class='paddingTop'>
                                <button class='button' type="submit" name="submit">Submit</button>
                                <button class='button' type="save" name="save">Save</button>
                                <button class='button' id='clear' type="reset" value="Reset" >Clear</button>
                            </td>
                        </tr>
                        <?php endif ?>
                    </section>
                </tbody>
            </form>
        </table>
    </article>
</main>
<script>
    <?php
    if (isset($_SESSION['request_alert'])) {
        echo 'alert("'.$_SESSION['request_alert'].'")';
        unset($_SESSION['request_alert']); 
    }
    ?>

    window.onload = ()=> {
        var inputs = document.getElementsByTagName('input');
        var textareas = document.getElementsByTagName('textarea');
        
        for (let i = 0; i < inputs.length; i++) {
            if(inputs[i].type == 'checkbox'){
                if (inputs[i].value == true) {
                    inputs[i].checked = true;
                } else {
                    inputs[i].checked = false;
                }

                inputs[i].onclick = () => {
                    if (inputs[i].checked) {
                        inputs[i].value = true;
                    } else {
                        inputs[i].value = false;
                    }
                }     
            }
        }

        <?php if($req['status'] == 1 || $req['status'] == 0): // Clear button functionality ?>
        document.getElementById('clear').onclick = (e) => {
            e.preventDefault()
            document.getElementById('bid').value = '';
            document.getElementById('bsid').value = '';
            for (let i = 0; i < inputs.length; i++) {
                if(inputs[i].type == 'checkbox'){
                    inputs[i].value = false;
                    inputs[i].checked = false;
                }  
            }
            for (let i = 0; i < textareas.length; i++) {
                textareas[i].innerText = '';
            }
        }

        <?php else: // disabled texareas when request is beeing proccess ?>
        for (let i = 0; i < textareas.length; i++) {
                textareas[i].disabled = true;
                textareas[i].placeholder = 'N/A';
        }
        for (let i = 0; i < inputs.length; i++) {
            inputs[i].disabled = true;
        }
        <?php endif ?>
    }


</script>