<?php
$wirte = preg_match('(w)', $lab['rights']);
?>

<script type="text/javascript" language="javascript">
    var columnsInfo = [{
            'data': 'eid',
            'render': function(eid) {
                if (<?= $_SESSION['g_user_eid'] ?> == eid)
                    return '---';
                else
                    return '<button class="btn" value="' + eid + '" data-toggle="close" onclick="inLineEdit(\'' + eid + '\')"><span class="material-icons">edit</span></button>';
            },
            'sortable': false,
        },
        {
            'data': 'eid',
            'render': function(eid, a, b) {
                if (<?= $_SESSION['g_user_eid'] ?> == eid)
                    return '---';
                else if (b['building3'])
                return '<button class="btn" onclick="confirmBox(\'Are you sure you want to delete request of this user \('+ eid +'\). User will be notified about this action\', \''+eid+'\', \'deleteRequest\')"><span class="material-icons">delete</span></button>';
                else
                    return '<span class="colorGray">N/A</span>';
            },
            'sortable': false,
        },
        {
            'data': 'eid',
            'render': function(eid) {
                if (<?= $_SESSION['g_user_eid'] ?> == eid)
                    return '---';
                else {
                    return '<button class="btn" onclick="confirmBox(\'Are you sure you want to delete this user \('+ eid +'\)\', \''+eid+'\', \'deleteUser\')"><span class="material-icons">block</span></button>';
                }
            },
            'sortable': false,
        },
        {
            'data': 'eid',
            'name': 'eid',
        },
        {
            'data': 'name',
            'name': 'name',
        },
        {
            'data': 'login',
            'name': 'login',
        },
        {
            'data': 'email',
            'name': 'email',
        },
        {
            'data': 'comments',
            'name': 'comments',
        },
        {
            'data': 'manager_id',
            'name': 'manager_id',
        },
        {
            'data': 'delegated_manager_id',
            'name': 'delegated_manager_id',
        },
        {
            'data': 'training_date1',
            'name': 'training_date1',
        },
        {
            'data': 'status1',
            'name': 'status1',
        },
        {
            'data': 'training_date2',
            'name': 'training_date2',
        },
        {
            'data': 'status2',
            'name': 'status2',
        },
        {
            'data': 'rights',
            'name': 'rights',
        },
        {
            'data': 'status',
            'name': 'status'
        },
        {
            'data': 'request_date',
            'name': 'request_date',
        },
        {
            'data': 'manager_comment',
            'name': 'manager_comment',
        },
        {
            'data': 'admin_comment',
            'name': 'admin_comment',
        },
        {
            'data': 'bid',
            'name': 'bid',
        },
        {
            'data': 'bsid',
            'name': 'bsid',
        },
        {
            'data': 'building3',
            'name': 'building3',
        },
        {
            'data': 'building2',
            'name': 'building2',
        },
        {
            'data': 'building1',
            'name': 'building1',
        },
        {
            'data': 'room4',
            'name': 'room4'
        },
        {
            'data': 'room3',
            'name': 'room3'
        },
        {
            'data': 'room2',
            'name': 'room2'
        },
        {
            'data': 'room1',
            'name': 'room1',
        }
    ];
    var mycoldef = [

        {
            targets: [11, 13, 21, 22, 23, 24, 25, 26, 27],
            "searchable": false,
            class: 'choose',
            'render': function(data) {
                if (data === 1)
                    return '<span class="material-icons colorGreen">done</span>';
                else if (data === 0)
                    return '<span class="material-icons colorRed">close</span>';
                else
                    return '';
            }
        },
        {
            targets: [7, 17, 18],
            'render': function(data) {
                if (data)
                    return '<i>' + data + '</i>';
                else
                    return '';
            }
        },
        {
            targets: [0, 1, 2],
            class: 'button',
            <?= (!$wirte) ? "'visible': false" : "'visible': true" ?>,
        },
        {
            targets: [3, 4, 5, 6],
            class: 'disbaled'
        },
        {
            targets: '_all',
            visible: true
        },
    ];
</script>
<main class="box">
    <article class='panel panel-default'>
        <div id='showHideIndicators' class="panel-heading">
            <b>Show/Hidde columns:</b><br />
        </div>
        <div class='panel-heading'>All users and requests<br>
            <small class="form-text text-muted">Note: You can hover over the column name for more details.</small>
        </div>
        <div class='panel-body'>
            <div class='table-responsive'>
                <table id="content_table" class='table table-borderoom2 table-striped'>
                    <thead>
                        <tr>
                            <th>Edit inline</th>
                            <th>Delete request</th>
                            <th>Delete user</th>
                            <th>Employee ID</th>
                            <th>Name</th>
                            <th>login</th>
                            <th>Email</th>
                            <th>Comments</th>
                            <th>Manager ID</th>
                            <th>Delegated manager ID</th>
                            <th>training1 date</th>
                            <th>status1</th>
                            <th>training2 date</th>
                            <th>status2</th>
                            <th>Rights</th>
                            <th>Request status</th>
                            <th>Request date</th>
                            <th>Manager comments</th>
                            <th>admin comments</th>
                            <th>BID</th>
                            <th>BSID</th>
                            <th>building3</th>
                            <th>building2</th>
                            <th>building1</th>
                            <th>room4</th>
                            <th>room3</th>
                            <th>room2</th>
                            <th>room1</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Edit inline</th>
                            <th>Delete request</th>
                            <th>Delete user</th>
                            <th>*Employee id</th>
                            <th>*Name</th>
                            <th>*login</th>
                            <th>*Email</th>
                            <th>*Comments</th>
                            <th>*Manager id</th>
                            <th>*Delegated manager id</th>
                            <th>*training date</th>
                            <th>status</th>
                            <th>*training date</th>
                            <th>status</th>
                            <th>*Rights</th>
                            <th>*Request status</th>
                            <th>*Request date</th>
                            <th>*Manager comments</th>
                            <th>*admin comments</th>
                            <th>*BID</th>
                            <th>*BSID</th>
                            <th>~building3</th>
                            <th>~building2</th>
                            <th>~building1</th>
                            <th>~room4</th>
                            <th>~room3</th>
                            <th>~room2</th>
                            <th>~room1</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <?php if ($wirte) : ?>
            <div class='panel-heading'>

                <div class="form-group">
                    <table align="center">
                        <thead>
                            <tr>
                                <td colspan='3'>
                                    <h3>Add new user</h3>
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <input type="text" name='nsn_data' class="form-control" id="nsn_data" placeholder="Enter nsn id / email / nsn login">
                                </td>
                            </tr>
                            <tr>
                                <td colspan='3'>
                                    <small class="form-text text-muted">Note: data will be pulled from ldap server.</small>
                                    <br />
                                    <button id='addUser' class='btn'>Add user</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        <?php endif; ?>
    </article>
</main>
<script>
    $('#addUser').click(function() {
        if ($('#nsn_data').val() != '') {
            $.ajax({
                type: "POST",
                url: '/database/requests/review/logic',
                data: {
                    'nsn_data': $('#nsn_data').val(),
                    'logic': 'addUser',
                },
                success: function(result) {
                    if ('User added' == result) {
                        successBox('User successfully pulled form LDAP.');
                        $('#content_table').DataTable().ajax.reload();
                    } else if ('User updated' == result) {
                        successBox('User successfully pulled form LDAP.');
                        $('#content_table').DataTable().ajax.reload();
                    } else {
                        errorBox('User not found! Please check croom2entials.');
                    }
                }
            });

        } else {
            alertBox('Input field is empty!');
        }
    });

    $('body').on('click', '[data-btn-message="deleteRequest"]', function(){
        $.ajax({
            type: "POST",
            url: './review/logic',
            data: {
                user_eid: $(this).val(),
                logic: 'deleteRequest',
            },
            success: function(result) {
                $('#content_table').DataTable().ajax.reload();
                successBox('User request succesfuly deleted');
            },
        });
    });

    $('body').on('click', '[data-btn-message="deleteUser"]', function(){
        $.ajax({
            type: "POST",
            url: './review/logic',
            data: {
                user_eid: $(this).val(),
                logic: 'deleteUser',
            },
            success: function(result) {
                $('#content_table').DataTable().ajax.reload();
                successBox('User succesfuly deleted');
            },
        });
    });

    function inLineEdit(eid) {

        $('#content_table tbody tr').each(function() {
            let tr = $(this);
            let button = tr.children().eq(0).children()
            if (button.val() == eid) {
                if (button.attr('data-toggle') == 'close') {
                    button.html('<span class="material-icons">cancel</span>');
                    button.attr('data-toggle', 'open')

                    let line = `
                    <td colspan='3'>
                        <button class='btn' value='` + eid + `' onclick='confirmBox("Are you sure you want update this user  (` + eid + `) data.", `+eid+`, "update")'><span class="material-icons">done</span></button>
                    </td>`;
                    let count = 0
                    $('td:visible', tr).each(function() {
                        if (!$(this).hasClass('button')) {
                            if ($(this).hasClass('disbaled')) {
                                var disable = 'disabled';
                            } else {
                                var disable = '';
                            }
                            if ($(this).hasClass('choose')) {
                                if ($(this).text() == 'done') {
                                    line += `<td><input class='form-control' name='` + columnsInfo[count]['name'] + `' type='text' value='1' ` + disable + ` /></td>`;
                                } else {
                                    line += `<td><input class='form-control' name='` + columnsInfo[count]['name'] + `' type='text' value='0' ` + disable + ` /></td>`;
                                }
                            } else {
                                line += `<td><input class='form-control' name='` + columnsInfo[count]['name'] + `' type='text' value='` + $(this).text() + `' ` + disable + ` /></td>`;
                            }
                        }
                        count += 1;
                    });

                    tr.after(`<tr>` + line + `</tr>`);
                } else {
                    button.html('<span class="material-icons">edit</span>');
                    button.attr('data-toggle', 'close');
                    tr.next().remove();
                }
                return 1
            }
        });
    }

    $('body').on('click', '[data-btn-message="update"]', function(){
        userInfo = {
            'logic': 'updateUser',
        };
        update_btn = $(this).val();
        $('#content_table tbody tr').each(function() {
            let tr = $(this);
            let button = tr.children().eq(0).children()

            if (button.val() == update_btn) {
                next_tr = tr.next();
                next_tr.children().each(function() {
                    let input = $(this).children()
                    if (input.attr("name")) {
                        if (input.hasClass('choose')) {
                            if ($(this).text() == 'done') {
                                userInfo[input.attr("name")] = 1;
                            } else {
                                userInfo[input.attr("name")] = 0;
                            }
                        } else {
                            userInfo[input.attr("name")] = input.val();
                        }
                    }
                });
                return 1;
            }
        });
        if (userInfo) {
            if (userInfo['manager_id'].length == 0 || userInfo['manager_id'].length == 8){
                if(userInfo['delegated_manager_id'].length == 0 || userInfo['delegated_manager_id'].length == 8 ){
                    if(userInfo['bid'].length <= 20){
                        if(userInfo['bsid'].length <= 20){
                            let regex = new RegExp('^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$');
                            if(regex.test(userInfo['request_date']) || userInfo['request_date'] == ''){
                                if(regex.test(userInfo['training_date2']) || userInfo['training_date2'] == ''){
                                    if(regex.test(userInfo['training_date1']) || userInfo['training_date1'] == ''){
                                        $.ajax({
                                            type: "POST",
                                            url: '/database/requests/review/logic',
                                            data: userInfo,
                                            success: function(result) {
                                                successBox('User data succesfuly updated');
                                                $('#content_table').DataTable().ajax.reload();
                                            }
                                        });
                                    } else {
                                        alertBox('Icorrect esd training date format!')
                                    }
                                }  else {
                                    alertBox('Icorrect esa training date format!')
                                }
                            }  else {
                                alertBox('Icorrect request date format!')
                            }
                        } else {
                            alertBox('Icorrect skawina badge id format!')
                        }
                    } else {
                        alertBox('Icorrect badge id format!')
                    }
                } else {
                    alertBox('NSN ID of delegated manager is incorrect!')
                }
            } else {
                alertBox('NSN ID of manager is incorrect!')
            }
        }
    });
</script>